/**
 * Category plus secret word. Everyone is shown the word; the imposter is shown
 * only the category, which is enough to bluff with and not enough to be safe.
 */
export type Secret = { category: string; word: string }

export const SECRETS: Secret[] = [
  { category: 'Instrument', word: 'Guitar' },
  { category: 'Instrument', word: 'Drums' },
  { category: 'Instrument', word: 'Piano' },
  { category: 'Instrument', word: 'Violin' },
  { category: 'Fruit', word: 'Pineapple' },
  { category: 'Fruit', word: 'Banana' },
  { category: 'Fruit', word: 'Watermelon' },
  { category: 'Fruit', word: 'Strawberry' },
  { category: 'Animal', word: 'Penguin' },
  { category: 'Animal', word: 'Elephant' },
  { category: 'Animal', word: 'Octopus' },
  { category: 'Animal', word: 'Crocodile' },
  { category: 'Animal', word: 'Hedgehog' },
  { category: 'Place', word: 'Airport' },
  { category: 'Place', word: 'Library' },
  { category: 'Place', word: 'Hospital' },
  { category: 'Place', word: 'Beach' },
  { category: 'Place', word: 'Cinema' },
  { category: 'Place', word: 'Supermarket' },
  { category: 'Sport', word: 'Swimming' },
  { category: 'Sport', word: 'Boxing' },
  { category: 'Sport', word: 'Tennis' },
  { category: 'Sport', word: 'Climbing' },
  { category: 'Sport', word: 'Cricket' },
  { category: 'Food', word: 'Pizza' },
  { category: 'Food', word: 'Sushi' },
  { category: 'Food', word: 'Pancakes' },
  { category: 'Food', word: 'Curry' },
  { category: 'Food', word: 'Ice cream' },
  { category: 'Job', word: 'Dentist' },
  { category: 'Job', word: 'Pilot' },
  { category: 'Job', word: 'Teacher' },
  { category: 'Job', word: 'Chef' },
  { category: 'Job', word: 'Firefighter' },
  { category: 'Vehicle', word: 'Submarine' },
  { category: 'Vehicle', word: 'Motorbike' },
  { category: 'Vehicle', word: 'Helicopter' },
  { category: 'Vehicle', word: 'Tractor' },
  { category: 'Weather', word: 'Thunderstorm' },
  { category: 'Weather', word: 'Snow' },
  { category: 'Weather', word: 'Fog' },
  { category: 'Object', word: 'Umbrella' },
  { category: 'Object', word: 'Toothbrush' },
  { category: 'Object', word: 'Mirror' },
  { category: 'Object', word: 'Candle' },
  { category: 'Object', word: 'Ladder' },
  { category: 'Object', word: 'Suitcase' },
  { category: 'At school', word: 'Homework' },
  { category: 'At school', word: 'Assembly' },
  { category: 'At school', word: 'Detention' },
  { category: 'At school', word: 'Exam' },
  { category: 'Clothing', word: 'Scarf' },
  { category: 'Clothing', word: 'Trainers' },
  { category: 'Clothing', word: 'Hoodie' },
  { category: 'Nature', word: 'Volcano' },
  { category: 'Nature', word: 'Waterfall' },
  { category: 'Nature', word: 'Desert' },
  { category: 'Nature', word: 'Rainforest' },
  { category: 'Space', word: 'Black hole' },
  { category: 'Space', word: 'Asteroid' },
  { category: 'Space', word: 'Astronaut' },
  { category: 'Household', word: 'Washing machine' },
  { category: 'Household', word: 'Fridge' },
  { category: 'Household', word: 'Vacuum cleaner' },
]
